### ISSUE TITLE
Technology stack for CCM

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#1]
Currently the tech stack followed internally are Python/Django. But with current CCM redesign that is not necessarily the ideal choices. One proposal is experiment with  Full stack Java script. 

CCM Design wireframes
https://github.com/tl-its-umich-edu/UX-Work/tree/master/ccm/wireframes

**Comment by chrisrrowland** [comment]
Did some experimenting with svelte/typescript/material [here ](https://github.com/chrisrrowland/svelte1)

**Comment by pushyamig** [comment]
We are moving forward with React stack and this issue served the purpose
