### ISSUE TITLE
Dealing with when user invalidates the oAuth grant in canvas, outside of CCM

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#101]
Test requests with using invalid Canvas token are properly redirected to OAuth flow
1. Launch application as normal.
2. Go to profile/settings in Canvas and delete all "Approved Integrations" entries for your API Developer Key.
3. Perform an action in the UI that involves a request to Canvas, checking that you are redirected to Canvas OAuth page.
4. Repeat steps 2 and 3 until all actions are tested.

Test requests involving a token refresh of an invalid Canvas token are properly redirect to OAuth flow

1. Launch application as normal.
2. Go to profile/settings in Canvas and delete all "Approved Integrations" entries for your API Developer Key.
3. Modify the expires_at value in the canvas_token record for your user in the database so it is in the past.
4. Perform an action in the UI that involves a request to Canvas, checking that you are redirected to Canvas OAuth page.
5. Repeat steps ii, iii, and iv until all actions are tested.

**Comment by ssciolla** [comment]
Okay, so based on how things are set up now, there are two different errors we need to handle, once the integration is removed from the Canvas side:

1) The user's Canvas Token is still considered fresh by the application, and the request using `CanvasRequestor` fails with a `401` "Invalid access token."

(will fill in details here)

2) The token is stale and needs to be refreshed, and the request from the `CanvasService` fails with a `400` "invalid_request" error.

```
2021-08-17T13:39:11.435Z - canvas.service.ts - error - Received unusual status code 400
2021-08-17T13:39:11.435Z - canvas.service.ts - error - Response body: {
  "error": "invalid_request",
  "error_description": "refresh_token not found"
}
Nest] 90   - 08/17/2021, 1:39:11 PM   [ExceptionsHandler] An error occurred while requesting or refreshing a Canvas OAuth access token. +577631ms
CanvasOAuthAPIError: An error occurred while requesting or refreshing a Canvas OAuth access token.
```

**Comment by melindakraft** [comment]
@ssciolla In my testing
Access CCM as a regular teacher user
In a different tab, delete the authorization
Click on the format gradebook option and no auth error is thrown. This behavior is different than the other CCM tools which always prompt me to reauth. It seems specific to the format gradebook tool and not hte order in which I click on the tools.

**Comment by melindakraft** [comment]
After talking with Sam, this is a pass. GEFF doesn't have any API calls so there is no authorization to validate.
