### ISSUE TITLE
Deal with CSP violation error when not launching from Canvas Vanity URL

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#103]
So we really don't know if we are going to implement Canvas Vanity URL in Prod and we are getting some errors related to Violation of Content Secure Policy(CSP) when launching CCM, We might need to deal with this in our NodeJS app.

Some research is needed how to do this in NodeJs. You can replicate the below error in the Canvas beta instance
![Screen Shot 2021-06-09 at 9 44 21 AM](https://user-images.githubusercontent.com/8579775/121366867-d1fe7380-c907-11eb-936b-3f5b40e3fad2.png)

**Comment by pushyamig** [comment]
1. x-frame option = allow all

**Comment by jonespm** [comment]
You used to be able to use X-Frame-Options ALLOW-FROM (and in some browsers ALLOWALL) to do this easily. This could be done with Helmet `helmet.frameguard(options)`. https://helmetjs.github.io/

However this is [marked as deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) by CSP frame-ancestors.

It looks like there's a helmet-csp package. https://www.npmjs.com/package/helmet-csp

I'm MyLA we're passing in instructure.com into `frame-src`. Many CSP policies have a fallback.

**Comment by pushyamig** [comment]
This is Non-issue. Thanks @jonespm further insights on this and analyzing this is something coming from Canvas not from CCM. 

it's just a [new feature](https://umich.beta.instructure.com/accounts/1/settings#tab-security) that is only an issue on beta. The security tab is only in beta, in test you can enable it canvas test and you don't see this option in Prod at all

comments from @jonespm 
For some reason this domain isn't added by default but they say it should be. "Canvas and Instructure domains are included automatically and do not count against your 50 domain limit."

The policy is "report only" so it only will display the error but have no effect
we added  the beta domain to allowed list. You might see this when Prod sync beta over the beta. 

But this cannot be reproduce locally, test, umich dev. Now after adding beta canvas domain we don't see this error any more. Again not coming from CCM but from Canvas

**Comment by zqian** [comment]
As Pushyami mentioned above, [The Security tab only displays in Account Settings](https://community.canvaslms.com/t5/Admin-Guide/How-do-I-manage-the-Content-Security-Policy-for-an-account/ta-p/149) if admin have enabled the Content Security Policy feature preview.

![image](https://user-images.githubusercontent.com/359944/146978178-8e0294e5-f1b9-4d7d-a264-c053f42878e1.png)

The "Content Security Policy" does not exist in UM Canvas Prod instance. Tested the setting in Canvas Beta environment was successful with the "Content Security Policy" turned on, and no error message in the console log.
