### ISSUE TITLE
Disallow application use/OAuth authorization by masquerading user

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#105]
"This is an interesting case I found out.
I tried to become user and  was able to authorize as him and generated the token. I feel this would be wrong. We might need to deal with this issue.

I looked up in the LTI substitution variable $Canvas.masqueradingUser.id, If launch is by user as him this variable won't be populated
i.e 
```
"https://purl.imsglobal.org/spec/lti/claim/custom": {
    "roles": "TeacherEnrollment,Account Admin",
    "login_id": "userA", // canvas_id= 56
    "course_id": 44444444,
    "become_user": "$Canvas.masqueradingUser.id",
    "is_root_account_admin": true
  },
```
But if the launch is via becoming an user this id get populated telling who the the masqueraded user is

```
"https://purl.imsglobal.org/spec/lti/claim/custom": {
    "roles": "TeacherEnrollment,Account Admin",
    "login_id": "userB", // Masqueraded user
    "course_id": 44444444,
    "become_user": 56, // this is the masquerading user 
    "is_root_account_admin": true
  },
```

By `become_user` variable we can identify this a masquerading launch and we can handle this case. There may be better ways to handle this but this is just 20 minutes of research"

_Originally posted by @pushyamig in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/92#discussion_r648301846_

In my (@ssciolla) opinion, we shouldn't allow any masquerading users to use the application. This will prevent users from making changes as other users -- and all the security and auditing problems that might introduce.

**Comment by pushyamig** [comment]
@melindakraft Team likes to hear your thoughts on this.

**Comment by pushyamig** [comment]
I am closing this since only people who can masquerade is root account admins and people can do that are trusted users. So decided to allow the become user feature into CCM from canvas. It is still a moot point if we need to allow root admins to authorize token generation Kaltura workflow allows it. I think We will cover in the documentation/ Training not to Authorize unless you really need to.
