### ISSUE TITLE
create API function for bulk-enrolling users

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#108]
## Requirements
* Accept POST requests to `sections/:sectionId/enroll`
* The section identified by `sectionId` must exist in Canvas and the user must have proper access to it.  This will not be checked.  If there are any errors from Canvas (e.g., section doesn't exist or the user doesn't have the proper access), they will be returned in the response from this API entry.
* List of users to be enrolled, along with their role, must be submitted as JSON array. The CSV of users, submitted to the UI by the application user, will be reformatted to JSON by the UI code.
  * Request body example:
    ```json  
    {"users":[
      {"loginId": "name1", "role": "StudentEnrollment"},
      {"loginId": "name2", "role": "TeacherEnrollment"}
    ]}
    ```
  * Values for `role` must be one of the following valid Canvas roles:
    * `StudentEnrollment`
    * `TeacherEnrollment`
    * `TaEnrollment`
    * `ObserverEnrollment`
    * `DesignerEnrollment`
  * Invalid roles will be rejected by the Canvas API.  Canvas errors will be relayed back to the CCM API user.
  * Values for `loginId` must be a U-M user uniqname or a U-M Friend account email address.  Use these rules, in this order:
    1. Email addresses ending with `@umich.edu` (this string should be configurable) will have the `@` and everything following it removed.
    2. During processing, email addresses will be converted to Canvas login ID format by replacing the `@` with `+`.
* Limit the number of users to be enrolled to 400 per request.  See Slack conversation (https://app.slack.com/client/T69CPPGNP/G0130F688N6/thread/G0130F688N6-1627054990.263100).  The limit should be configurable.
* Notifications should not be sent to users when they are enrolled in a section.  The request to the Canvas API must include `"notify": false`.
* Users should not be invited to the course, they should be added directly to the course by setting the enrollment state to `"active"`.
* Example request:  
  ```sh
  curl 'https://canvas-test.it.umich.edu/api/v1/sections/543762/enrollments' \
    -H 'authorization: Bearer 1770~u6…' \
    -H 'content-type: application/json' \
    --data-raw '{"enrollment":{"user_id":"sis_login_id:bjensen","type":"StudentEnrollment","enrollment_state":"active","notify":false}}'
  ```  
  See API reference: https://docs.google.com/spreadsheets/d/1pm5y9FX0zrDX7Zy3mOyDLxmA-iKoWfmlxvbtNkWg6Zw/edit#gid=578161201&range=C9
* Users are specified by uniqname or Friend account email address (`@` → `+` transformed), which Canvas refers to as the user `login_id`.  This function must prefix each uniqname/email with the string `sis_login_id:` to refer to users in the Canvas API enrollment request.  (See: https://canvas.instructure.com/doc/api/file.object_ids.html)
* Validations
	* Each section must exist.  Handled by the Canvas API enrollment request.
	* Each user must exist.  Handled by the Canvas API enrollment request.

**Comment by pushyamig** [comment]
@lsloan this would be you next issue to work on after #141. This might need bit research #109  on how the handle deal with enrolling up to 200 users with one request.

**Comment by pushyamig** [comment]
@lsloan, @chrisrrowland will be working on the UI #107 for this, so this issue will be next good issue to look into

**Comment by lsloan** [comment]
> @lsloan this would be you next issue to work on after #141. This might need bit research #109 on how the handle deal with enrolling up to 200 users with one request.

It appears that #109 is blocking this issue, so that issue seem to be next, technically.

**Comment by lsloan** [comment]
Amendment to my earlier comment:  Although #109 is blocking this issue via ZenHub, that other issue is really an enhancement to this one.  It seems like the blocking should be the other way around.

I'll implement this issue first, with the assumption that enrolling multiple users will not take a long time.  Then, as an enhancement, implement #109 to improve its performance.

**Comment by lsloan** [comment]
As I implement a solution for this issue in #165, it looks likely that #109 will not be necessary.
