### ISSUE TITLE
handle simultaneous use in multiple courses

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#113]
## Problem

When CCM is launched, the ID of the course from which it was launched is stored in the session.  Subsequent launches from other courses within the same browser (e.g., the user launches from another tab or window) will cause the stored course ID to be overwritten with the ID of the last course to launch the app.  Using the tab/window with the earlier launched app may make it refer to the later launching course.

## Possible solutions

1. Documentation should warn users not to use CCM simultaneously from multiple tabs/windows within a browser.
2. Use some browser window-specific cookie/data to keep track of which course the app is being used with.  This may not be supported the same way across all browsers.
3. Perhaps the frontend can keep track of which course from which it was launched (e.g., in React globals) and always pass the course ID along with API requests.  API entries should require the course ID as part of each request (e.g., "`/api/hello/𝒏𝒏𝒏𝒏𝒏𝒏`", "`/api/hello/course/𝒏𝒏𝒏𝒏𝒏𝒏`", or in the request body).
4. When launch requests are received, if the user has a "recent" session open with a different course number, warn the user.  Either tell them that their session with the other course will be terminated or prompt them whether they want to continue their session with a new course before overwriting the course ID.

Solutions that try to support simultaneous use (items 2 and 3) will probably require restructuring of the data in the session.  That is, the session could contain a list of courses associated with it.  Each of the courses in the list would contain data about that course, like the user's role within the course (if they're not a Canvas admin), etc.

**Comment by lsloan** [comment]
I didn't know whether "bug" was an appropriate label for this issue.  Feel free to change it.  Also feel free to change the problem description and possible solutions.

**Comment by pushyamig** [comment]
Need testing to see if this is a real issue or not

**Comment by pushyamig** [comment]
@melindakraft Can you test this use case to see if this is a real issue or not?

**Comment by melindakraft** [comment]
In testing as KalturaK in multiple course tabs at the same time I did not encounter any problems. The user was able to perform the tasks appropriate to the role in the course and those tasks did not generate errors. I am going to assume this is not a real issue until we receive reports from our users.
