### ISSUE TITLE
Migration error possibly related to camelCase table names

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#126]
While working on issue #100, I was playing around with migrations, and I encountered a strange error. After I started up the application from an empty database, stepped back once using `down`, I saw this when attempting to reapply the migration.

```
docker exec -it ccm_web node -r ts-node/register server/src/migrator up
2021-06-16T20:03:32.729Z - config.ts - info - Value undefined for SESSION_SECRET is invalid; using fallback SESSIONSECRET
2021-06-16T20:03:32.731Z - config.ts - info - Value undefined for LTI_ENCRYPTION_KEY is invalid; using fallback LTIKEY
2021-06-16T20:03:32.811Z - migrator.ts - info - Running migrations CLI...
Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
Executing (default): SHOW INDEX FROM `SequelizeMeta`
Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
2021-06-16T20:03:32.887Z - migrator.ts - info - {
  "event": "migrating",
  "name": "2021.06.08T13.39.45.create-canvas-token.ts"
}
Executing (default): CREATE TABLE IF NOT EXISTS `canvasToken` (`id` BIGINT NOT NULL auto_increment , `userId` BIGINT NOT NULL, `accessToken` VARCHAR(255) NOT NULL, `refreshToken` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `user` (`id`)) ENGINE=InnoDB;

Error: Table 'ccm.canvastoken' doesn't exist
2021-06-16T20:03:33.098Z - migrator.ts - info - Migration tasks ran!
```

We have seen some other strange errors related to casing in table names, which may or may not be related. I think we should investigate whether to use underscored table names, as these are all lowercase and may avoid some of these issues ( a s well as maintain consistency with other projects and follow general MySQL naming conventions). Sequelize supports using an `underscored` option so we can still use camelCase with model methods. We may have to modify or re-create existing migrations (which is not ideal), but should theoretically be okay as we have not deployed to production.

**Comment by lsloan** [comment]
That error is _**EXACTLY**_ the one I had been seeing.  Others didn't have this problem while I did.  Perhaps when MySQL was installed in my environment, it was installed with case-sensitivity option (or not) while others had the opposite option.  Why Docker would install mine differently than others', I don't know.  Apparently now that option is being set for more people.

**Comment by pushyamig** [comment]
Test passes
