### ISSUE TITLE
Fix error handing with `HttpService` and `axios`, add `axios` and `got` as explicit dependencies

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#136]
While working on #100, I identified a couple of issues with how we (I, really) are handling Canvas API requests. I'll describe each one separately below, but they are related and I plan to address them all at once as part of the refresh token work.

- `HttpService` is a wrapper for `axios`, and it appears that like `got`, errors are thrown on irregular status codes. So the handling of irregular codes needs to be moved in `CanvasService` into the `catch` block for both the initial token creation and the refreshing. `axios` has an `isAxiosError` type guard we can use to check the `error` object for a response.
- Because in both the case of `axios` and `got` we need to use types or functions from those libraries, it seems like a best practice to add both libraries as explicit imports to the project. This shouldn't increase our number of libraries, but it will add some maintenance as those will need to be kept in sync with `@nestjs` and `@kth`.

Long term, we might want to try using only one HTTP request library, but since `@kth` depends on `got` and NestJS depends on `axios`, it doesn't save us a dependency to do this, just maybe makes the code more consistent.

**Comment by pushyamig** [comment]
I have been testing various API call with error return and I Don't see any issues caused by this refactoring. On that note I will pass this.
