### ISSUE TITLE
get course section API function

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#141]
Provide an API function to get course sections. This will be used by features like:

* [Adding UMich users](https://github.com/tl-its-umich-edu/UX-Work/blob/master/ccm/wireframes/add_user_feature/add_um_user_sc.pdf)
* [Adding non-UMich users](https://github.com/tl-its-umich-edu/UX-Work/blob/master/ccm/wireframes/add_user_feature/add_nonUM_user_sc.pdf)
* [External tool Gradebook converter](https://github.com/tl-its-umich-edu/UX-Work/blob/master/ccm/wireframes/gradebook_feature/third_party_gradebook.pdf) 

The implementation must:

1. GET course sections from Canvas
  ~https​://umich.test.instructure.com/api/v1/courses/200?include[]=sections&include[]=total_students~
  The sample request given above **_WILL NOT_** give the number of students for each section.  It will give only the number of students in the **_COURSE_**.  Most likely, additional queries will need to be run to get the number of students in each section.
1. If Canvas' response is broken into multiple pages, assemble all the pages to be returned as a single response
1. Return for each section its name, ID, and number of enrollments

**Comment by lsloan** [comment]
> @lsloan Can you Please work on this issue next after #140

Yes, right after #91.

**Comment by pushyamig** [comment]
@lsloan I think this API call was giving all section including students list in course 
https://canvas-test.it.umich.edu/api/v1/courses/405505/sections?include[]=total_students&include[]=enrollments&include[]=sections

Can you try this instead?

```
{
        "id": 436180,
        "course_id": 405505,
        "name": "ACC 301 Section 001",
        "start_at": null,
        "end_at": null,
        "created_at": "2020-07-10T13:13:49Z",
        "restrict_enrollments_to_section_dates": false,
        "nonxlist_course_id": null,
        "sis_section_id": "",
        "sis_course_id": "",
        "integration_id": null,
        "sis_import_id": 9948,
        "total_students": 80
    },
```

**Comment by lsloan** [comment]
@pushyamig, yes, that's what I'd already figured out.
