### ISSUE TITLE
Deny access to CCM tool with Grader,Librarian, participant, Tool installer roles

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#142]
Grader, Participant, Tool installer and Librarian has access to the CCM tool since LTI configuration `"visibility": "admin" ` option seems to be giving it to then. This [document](https://docs.google.com/spreadsheets/d/1pm5y9FX0zrDX7Zy3mOyDLxmA-iKoWfmlxvbtNkWg6Zw/edit?ts=6009bad2#gid=1360549473) list who has access to CCM

The UI don't give any feature access but these user ending up in Canvas Oauth workflow which they shouldn't be going through. Nothing wrong but unnecessary 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/8579775/123477686-65a09700-d5cc-11eb-83e6-d9672bd60143.gif)

**Comment by pushyamig** [comment]
@melindakraft What are your thoughts on this? how this should be handled?

**Comment by melindakraft** [comment]
We should offer a message such as "Your role in this course does not allow access to this tool." (we can wordsmith)

**Comment by melindakraft** [comment]
Maybe the better approach is to allow designated roles and the rest are blocked by default. This will prevent future roles from getting access.
