### ISSUE TITLE
Remove toy `ConsumerTest` component and associated backend route 

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#145]
The `ConsumerTest` component and backend `api/hello` route seem no longer necessary, since we are now fetching and putting real data. I'm going to remove this to un-clutter the UI and `api` module in the backend.

**Comment by pushyamig** [comment]
Test passes

**Comment by melindakraft** [comment]
I don't know how I would validate this as complete, but I see @pushyamig has already tested.

**Comment by pushyamig** [comment]
Yes, This should be part of QA-Dev testing, sorry if that is not.
