### ISSUE TITLE
User.canvasToken has wrong type for when it doesn't exist

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#149]
While working on #139, I discovered that I had incorrectly typed the `canvasToken` field on the `User` model. I thought that when the relation didn't exist, `User.canvasToken` would be `undefined`. However, it actually is `null`. This hasn't posed a problem yet because of a fluke in the `CanvasService.findToken` method where I was accidentally sometimes returning `null` when I thought it was truthy. See below on line 128:
https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/c3076b6f0bb2c469060638da59cd485b0cb860f0/ccm_web/server/src/canvas/canvas.service.ts#L122-L130

The type on `User.canvasToken` should instead be changed to `canvasToken!: CanvasToken | null`. This shouldn't require any migration changes. You can confirm that `null` is the expected type by logging any `User` instance before the OAuth flow is initiated.

Side note: I plan to get rid of `findToken` in other refactoring, but I feel should be fixed first.

**Comment by pushyamig** [comment]
@ssciolla this fix is not relevant anymore. Lot of things got refactored from this and the issue also states that the function returning wrong types will be refactored. Looks like it is. Should I mark this as done?
