### ISSUE TITLE
Sending a better error response Object

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#156]
The need for this issue came up as part of this PR bulk creating section see [here](https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/154#pullrequestreview-706497557), where response would contain multiple responses. The issue aim for generalizing the Error Response Object for all the Canvas API's

The Proposal is `{"statusCode":404,"errors":[{"message":"No response body was found.","failedInput":"403334"}]}`

The `failedInput` represents input that user provided, like for fetching the course name, it would be the course ID. Updating the course name it would be course new name. In case of creating new sections, it would be section name. The idea is that based on the request the respective feature API ( like getCourseName, putCourseName etc) will know how to deal with the errors

Note: This is code refactoring and get and put course name is not doing anything with returned response and I am going to keep it that way

**Comment by jonespm** [comment]
It might be worth looking into https://www.npmjs.com/package/http-problem-details and using custom types rather than trying to use custom codes. I'd just return some 5xx if the failure is from a response from Canvas API and 4xx if the error is something wrong with the request that our server was able to respond with.

**Comment by lsloan** [comment]
_Posted by @pushyamig in https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/156#issue-945302924_
> The `failedInput` represents input that user provided, like for fetching the course name, it would be the course name.

I think you mean `failedInput` would contain the course **_ID_**, not its **_name_**.

**Comment by pushyamig** [comment]
> Posted by @pushyamig in #156 (comment)
The failedInput represents input that user provided, like for fetching the course name, it would be the course name.
I think you mean failedInput would contain the course ID, not its name.

Yes, I have updated my description

**Comment by pushyamig** [comment]
The way the error object is sent to frontend is changed/expanded after this PR. 
I have tested with various features the error object and I can say things are working as expected.
