### ISSUE TITLE
Fix types for `list`, `listPaginated` in `localTypes/@kth/canvas-api`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#158]
When reviewing #147 and thinking about pagination, I realized the types I had initially added for the `list` and `listPaginated` methods for the KTH requestor object `CanvasApi` were wrong. Looking at the documentation (https://github.com/KTH/canvas-api/blob/master/docs/API.md#CanvasApi-list) and [source code](https://github.com/KTH/canvas-api/blob/master/src/index.js), these methods actually return asynchronous [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator), which are further augmented with another method. I had trusted the types from an auto-generated version one. These need to be fixed, and we should use generics like the other methods to help us infer the data returned from the API.

https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/684da1c10c91ad2fd7062ac76e4badfe30a03bd9/ccm_web/server/localTypes/%40kth/canvas-api/index.d.ts#L29-L32

**Comment by pushyamig** [comment]
With the upgrade of canvas API library to `"@kth/canvas-api": "^4.0.0-1", we don't maintain local type as we do for Ltijs. So this issue is not relevant any more.

Test passes
