### ISSUE TITLE
Canvas API errors are mishandled

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#169]
While working on #108, I submitted enrollment data with an invalid role `type` of `fubar`.  The CCM API returned a response like:

```txt
{
  "statusCode": 400,
  "errors": [
    {
      "canvasStatusCode": 400,
      "message": "Response body had unexpected shape: {\"message\":\"Invalid type\"}",
      "failedInput": "[object Object]"
    }
  ]
}
```

I tried the same request using the Canvas API directly and this is the response it returned:

```txt
HTTP/2 400

{"message":"Invalid type"}
```

Somewhere along the way in the error handling, useful information is being lost.  `failedInput` should contain the input that caused the error.

Also, the "shape" of the response from Canvas shouldn't be "unexpected".  It's from a response with an HTTP 400 status code.  That's known to be an error.  A shape of `{"message":"…"}` **_should_** be expected.

**Comment by ssciolla** [comment]
@lsloan, you are free to try incorporate more "expected shapes" into the error processing. I started with the one I had seen (i.e. `{ errors: { message: "some string" } }`), but I have seen other shapes, particularly when validation fails. This is yet another case that could be handled. You are seeing the fall-through. In that sense, maybe the "bug" label here is debatable.

These are the relevant files if you want to add more expected body shapes. See `parseErrorBody` and the associated type guards.

https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/main/ccm_web/server/src/canvas/canvas.interfaces.ts
https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/main/ccm_web/server/src/api/api.utils.ts

I also see in your PR that you are casting a `user` object to a string using `String` before passing to `failedInput`. If you want more data shown, you can use `JSON.stringify(user, null, 2)`.

**Comment by lsloan** [comment]
Yes, maybe `bug` is not an appropriate label if different API entries or different circumstances give different response formats.

**Comment by pushyamig** [comment]
test passes
