### ISSUE TITLE
Feature: Bulk Enrolling of user

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#18]
This is Admin/Subaccount/Service center only Feature. Note: Service Center people have Support Consultant role which is a level of Root account privilege. Sub account admins have highest privileges in a sub account and or not allowed access to other sub accounts in canvas

For workflow guideline follow [Wireframes](https://github.com/tl-its-umich-edu/UX-Work/blob/master/ccm/wireframes/add_user_feature/add_um_user_sc.pdf) and accessibility Mock up [here](https://github.com/tl-its-umich-edu/UX-Work/blob/master/ccm/wireframes/accessibility_supported_wireframes/add_um_user_sc_aria.pdf) 

**Description:** 
1. Show the list of sections in the course
2. user can create a section to add a user or chose the existing one. Note: Section might be created as part of bulk creation process.
3. This process needs to take a simple CSV and create section. We should expect that we might add a large users to a course. This might needs to run as a background process and notify user once done.
4. User will provide Uniqname(sis_login_id) and role in the csv file
5. In one csv file we can expect a request to add 400(rows) user to a section, so this would run as an background and send an email to user. 
6. Research need to be made how to run it as a background process in NodeJs. Since node is single threaded but we should leverage concurrency behavior of it.  

Note: User should be informed from the UI that course invitations are sent for clarity.

Sample CSV file that user will [users-sections (4).csv](https://github.com/tl-its-umich-edu/canvas-course-manager-next/files/7068431/users-sections.4.csv)

**API calls**
https://umich.test.instructure.com:443/api/v1/sections/485428/enrollments?enrollment[user_id]=sis_login_id:studentb&enrollment[type]=StudentEnrollment

https://umich.test.instructure.com:443/api/v1/courses/232623/sections

Here is the detailed [API](https://docs.google.com/spreadsheets/d/1pm5y9FX0zrDX7Zy3mOyDLxmA-iKoWfmlxvbtNkWg6Zw/edit#gid=578161201) DOc

**Modification to UI from original Mockups:**
1. Make it a scrollable list instead of Pagination list of sections
2. Adding a search textbox on the UI searching for section
3. `users` text should be replaced with `students` for showing the count of students in a section

**Comment by melindakraft** [comment]
@pushyamig Discuss if we should have a feature switch for enabling/disabling Canvas notifications to the user when they've been added to a course for the first time. SIS doesn't send notifications, which admins like, but there may be use cases where sending notifications is desired. Perhaps we can ask the stakeholders.

**Comment by pushyamig** [comment]
> Discuss if we should have a feature switch for enabling/disabling Canvas notifications to the user when they've been added to a course for the first time.

By default the API doesn't send the notification but if we have to give a choice to the user then we can have checkbox then in the UI and in the API we can use the parameter `enrollment[notify]` to enable notification.

We can put his under agenda item in stack-holder meeting

**Comment by pushyamig** [comment]
> Discuss if we should have a feature switch for enabling/disabling Canvas notifications to the user when they've been added to a course for the first time. SIS doesn't send notifications, which admins like, but there may be use cases where sending notifications is desired. Perhaps we can ask the stakeholders.

Based on the above comment, I have created an issue and is out of scope for this phase of CCM @chrisrrowland 
https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/138
