### ISSUE TITLE
Enforce 1:1 relationship between `User` and `CanvasToken`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#184]
While working on issue #101, I realized that we are not enforcing the relationship between `User` and `CanvasToken` as 1:1, even though that is how it is typed using `sequelize-typescript`. We probably want to add a `UNIQUE` constraint to the foreign key `canvas_token.user_id` to ensure this is enforced at the database level. There are likely other ways to do this, but this seems to perhaps be the least disruptive.

**Comment by pushyamig** [comment]
Test passes, I see unique constraint applied to canvas_token table
select distinct CONSTRAINT_NAME from information_schema.TABLE_CONSTRAINTS where table_name = 'canvas_token' and constraint_type = 'UNIQUE';
