### ISSUE TITLE
Handle cleanly when user hits "Cancel" on Canvas authorize prompt

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#187]
As the OAuth flow currently exists, if the user hits "Cancel" when they reach Canvas, the application errors out. Because the returned URL query has only an `error` key, it's not considered a "bad" query, and we end up making an invalid call to request a Canvas token (resulting in a `500` error on the request to `canvas/returnFromOAuth`).

Work on issue #101 is somewhat adjacent to this. We either need to show an error page, or redirect back to the application which then restarts the Canvas OAuth flow.

**Comment by ssciolla** [comment]
Something like this should fix part of the bug, but we probably want to actually redirect the user somewhere if this happens
https://github.com/ssciolla/canvas-course-manager-next/commit/8c6b185b9e90ac09d77d59bdd39f26c1fb032ee2

**Comment by melindakraft** [comment]
Tested. Fails gracefully.

**Comment by pushyamig** [comment]
> Fails gracefully.

Issue resolved or not working as expected?

**Comment by melindakraft** [comment]
Works as expected.

*Melinda Kraft, Business Systems Analyst Lead*

*ITS Teaching & Learning*

Ann Arbor, MI 48109-3704

734/763-0509 <+17347630509> | she, her, hers
[image: A button with "Hear my name" text for name playback in email
signature] <https://www.name-coach.com/melinda-kraft>


*Need help with online instruction? Join the Teaching Online with Canvas
Workshops: From Good to Great!
<https://its.umich.edu/training/canvas> | Workshop Video Playlist
<https://www.mivideo.it.umich.edu/playlist/dedicated/137537371/1_bc51ybxg/1_fart74iy>*

**Comment by pushyamig** [comment]
Cool. In that case you need to move this issue to Done column in the project(Kanban) board [here](https://github.com/tl-its-umich-edu/canvas-course-manager-next/projects/1)

Or in the issue look for the `Projects` section and chose `Done` option and that also put in the Done column in Kanban board
![Screen Shot 2022-01-11 at 2 41 21 PM](https://user-images.githubusercontent.com/8579775/149010683-78c6df8a-f80d-41f0-9625-af8775750528.png)
