### ISSUE TITLE
Add page/content prior to Canvas OAuth redirect

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#189]
I think it might be reasonable from a UX perspective to add a banner or alert here instead that links to `/canvas/redirectOAuth`, telling the user that the Canvas API integration is missing and that they need to go through the OAuth flow. With the changes I've made, this would also be show to the user the first time they access CCM. What do people think?

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/183#discussion_r705500715_

This was discussed in meetings, and the UX team is recommending some kind of intermediary/interstitial page or content that tells the user why they are being redirected. My current thinking is this will be shown both when the user joins the first time, and if they are redirected because of a removed integration (see #183).

I have a prototype in a branch (https://github.com/ssciolla/canvas-course-manager-next/commit/31ad4318ab477af4fe9099776eb55d983edb0e6b), and Janel has provided some mockups with modified language.

Questions:
- Should the page include the home breadcrumb?
- What is the exact preferred language? What are the overarching design principles here? Simplicity? Clarity? Ease of use?
- What should the button `aria-label` text say?

**Comment by melindakraft** [comment]
I like the authorization page message, and it gives a good spot to redirect back to if the user Cancels the auth. The message, however, needs some work as end users will have no idea what "This tool is not integrated with Canvas" means.

Can we change the first line to read something along lines of:
"This is third party tool. You must authorize this tool before you can use it."

**Comment by melindakraft** [comment]
Created new issue for the language change.
