### ISSUE TITLE
refactor API `enrollUsers()` method to accept list of `sectionUsers`

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#193]
Minor API design question: should `enrollUsers` accept the list of `sectionUsers`? Then it could be re-used more effectively. I guess at that point, it might be more of a `SectionHandler` object that could do other section-related operations. Maybe these are niceties that are not necessary at this point, but it could get us closer to a `cavnvasapi`-like interface.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/165#r702143192_

---

It's a better design than the one used for the creation section support code, which was the pattern for the bulk enrollment support code.  It would allow for the handler's methods to be used again within the same invocation without calling the constructor again.

**Comment by pushyamig** [comment]
Refactoring is not impacted by functionality. test passes
