### ISSUE TITLE
remove hard-coded got retry `statusCodes`

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#194]
got@11.8.2 doesn't appear to have any `statusCodes` defined by default, which is probably why its retry feature didn't work as I expected until after I added `403`.  I'm hard-coding the list with the codes from got@12 and adding `403`.  In the future, we can replace the hard-coded list by replacing it with something like `defaultInternals.retry.statusCodes.concat(403)`.

_Originally posted by @lsloan in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/165#discussion_r710448639_

---

As @ssciolla pointed out, got@11.8.2 **_DOES_** have a default list of status codes for retry.  I'm not sure why I didn't see this when I searched its GH repo.  It turns out my IDE is probably "helpfully" ignoring JS files when there are TS files with similar names, so that's why I didn't see it when I used that to search the installed module.

Lesson learned:  grep never lies.

**Comment by pushyamig** [comment]
Test passes. Don't see the hard coded status codes in the code
