### ISSUE TITLE
User not informed of upload file size limits

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#197]
@pushyamig wrote…
We want only to handle 400 users enrollments to section. A simple text some where along with the sample download file would be useful. Also throw a validation error after the file upload if saw > 400 user 

---

@lsloan wrote…
Users need to be informed of the file size limits when uploading data for the following features:

* "Create Sections" — 60 sections — Also see #217
* "Add UM Users" — 400 users
* "Canvas Gradebook Formatter" — Does this have a limit?

Implementation notes:

* As mentioned in #217, checks of file sizes need to occur in the UI **_AND_** the API.
* Limits should be a configuration item in `.env` and available to both UI **_AND_** API code.

**Comment by ssciolla** [comment]
We need to fix this in a few of the other features.

**Comment by pushyamig** [comment]
Test passes.
