### ISSUE TITLE
Improve `APIErrorData` typing

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#206]
Yeah, the typing needs to be improved here for sure in a couple ways. Probably it should be something like:

```
export interface APIErrorData {
  statusCode: number
  error?: string
}

export interface ApplicationAPIErrorData extends APIErrorData {
  message?: string | string[]
  redirect?: string
}

export interface CanvasAPIErrorData extends APIErrorData {
  errors: APIErrorPayload[]
}
```

with some maybe some type guards. This is indeed a separate issue.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/205#discussion_r718497669_

In reference to the `APIErrorData` types in the frontend. Some modifcations to the backend may also make sense to increase consistency in data returned.

**Comment by pushyamig** [comment]
Thanks @ssciolla for opening the issue

**Comment by pushyamig** [comment]
Test Passes. I don't see any typing errors
