### ISSUE TITLE
Tweak language shown to unauthorized student users and unauthenticated users

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#209]
**Background:** 
Currently, if you navigate to the application's URL directly, the user is shown "You were not properly authenticated to the application." @melindakraft thinks this language should be tweaked to be a bit more user-friendly and link to documentation.

Similarly, if an authenticated student user happens to launch the tool (going to the external tools URL directly), they should see a similar user-friendly unauthorized message and a link to documentation.

@melindakraft will think about and provide what the messages should say.

**Text changes:**

Access Denied.

To use U-M Course Manager you must have a course management role in this course.

If you believe this message is in error, please contact 4help@umich.edu(https://its.umich.edu/help)

**Comment by melindakraft** [comment]
How about something like:

Access Denied. 

To use U-M Course Manager you must have a course management role in this course. 

If you believe this message is in error, please contact 4help@umich.edu (include link to ITS help page).

**Comment by ssciolla** [comment]
@pushyamig, can you assess whether what to do about this issue now that @zqian added that code to block these users at the level of the LTI service. Maybe we just want to tweak the language there, or we could redirect them to the root as we suggested already, and change the "You were not properly authenticated page..."

**Comment by pushyamig** [comment]
The ITS help link to use is https://its.umich.edu/help. as suggested by @melindakraft
