### ISSUE TITLE
"Create Sections" fails with large input

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#217]
# Problem

The "Create Sections" feature failed when given a file of 99,999 sections to create.  Sample file: [sections2.csv](https://github.com/tl-its-umich-edu/canvas-course-manager-next/files/7313298/sections2.csv)

The UI was able to parse the large file and show the rows on the page.  After submitting, the UI said…

> The last action failed with the following message: Internal server error

The server console output had the error…

```
ccm_web     | [Nest] 102   - 10/08/2021, 6:01:50 PM   [ExceptionsHandler] request entity too large +481950ms
ccm_web     | PayloadTooLargeError: request entity too large
ccm_web     |     at readStream (/base/node_modules/raw-body/index.js:155:17)
ccm_web     |     at getRawBody (/base/node_modules/raw-body/index.js:108:12)
ccm_web     |     at read (/base/node_modules/body-parser/lib/read.js:77:3)
ccm_web     |     at jsonParser (/base/node_modules/body-parser/lib/types/json.js:135:5)
ccm_web     |     at Layer.handle [as handle_request] (/base/node_modules/express/lib/router/layer.js:95:5)
ccm_web     |     at trim_prefix (/base/node_modules/express/lib/router/index.js:317:13)
ccm_web     |     at /base/node_modules/express/lib/router/index.js:284:7
ccm_web     |     at Function.process_params (/base/node_modules/express/lib/router/index.js:335:12)
ccm_web     |     at next (/base/node_modules/express/lib/router/index.js:275:10)
ccm_web     |     at /base/node_modules/express-session/index.js:506:7
ccm_web     |     at /base/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:22:7
ccm_web     |     at runMicrotasks (<anonymous>)
ccm_web     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

# To-Do

Check whether the "Add UM Users" feature is also affected in this way.

# Solution

The solution for this has several parts:

* The error above indicates the problem was in sending the large input to the API.  Therefore, because the UI was able to handle the large input, it should give an error that the input is too long before the user is given the option of submitting it.
* The `CreateSectionsDto` should have a limit to disallow any input it received that is too large.  See `SectionUsersDto` for an example.
* Similar to issue #197, the user needs to be informed that the maximum number of sections they can upload is 60.

**Comment by pushyamig** [comment]
@lsloan , Thanks for testing this. I saw that you already put this in ICE box pipeline. We only support 60 sections that we are not anticipating it will grow more than that since we don't have a use case for this

**Comment by zqian** [comment]
It turns out this issue has been fixed already with [issue 197](https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/197): 

- There is no error message shown in the log file
- The following warning message is shown in CCM UI "The CSV file has too many records. The maximum number of non-header records allowed is 60."

**Comment by pushyamig** [comment]
@zqian We also want to add a BE validation apart from FE. That's what team discussed during the review

**Comment by pushyamig** [comment]
Test pass:
I tested through Swagger UI that if more sections request put it than the limit (which is 60) i see a validation error

```
{
  "statusCode": 400,
  "message": [
    "sections must contain not more than 60 elements"
  ],
  "error": "Bad Request"
}
```
