### ISSUE TITLE
Building Block: Adding user authorizing oauth Process 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#22]
We will be using the Scoped token for this process what that mean we need user authorize with OAUTH 2 workflow approving the token generation and will be storing it those in the Database and will be using refresh token. 

This need a creating of Developer API key in the canvas console. 

https://canvas.instructure.com/doc/api/file.developer_keys.html
https://canvas.instructure.com/doc/api/file.oauth.html
https://canvas.instructure.com/doc/api/file.oauth_endpoints.html

**Comment by jonespm** [comment]
Based on the https://canvas.instructure.com/doc/api/file.developer_keys.html docs, you have to request specific scopes and Canvas will return a 401 if the user does not have access to the specific scopes. 

This still will not guarantee that calls to that API will return the same results for all users but at least will be an early failure check. 

It's worthwhile to consider the "Other considerations" for when Scopes are added/removed.
