### ISSUE TITLE
Upgrade Material UI

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/canvas-course-manager-next#220]
Version [5.0](https://mui.com/versions/) of react material was recently released.

**Comment by ssciolla** [comment]
Material UI 5 includes quite a few changes, many centered around styling, but there is a migration guide and some automatic code modification provided it seems: https://mui.com/guides/migration-v4/

**Comment by ssciolla** [comment]
There is this issue in `React.StrictMode` when using `Backdrop` with Material UI 4 during local development. Let's check to see if this is resolved when we update to version 5. https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/75#issuecomment-950954119

**Comment by ktowneUM** [comment]
create sections was tested
