### ISSUE TITLE
Tweak Gradebook Tools feature names, descriptions to be action-oriented, consistent with other features

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#228]
Right now the gradebook tools are named and described in a different way from the other features. They are named using a "{do something}er" format (e.g. "Gradebook Formatter"), while the other features use an action-oriented imperative like "Add UM Users" or "Create Sections". We might consider changing the gradebook feature titles so that they an imperative (e.g. "Gradebook Formatter" to "Format Gradebook"). The descriptions on the cards could also use the "Format" rather "Formats" language to be consistent with the other descriptions.

![Screen Shot 2021-10-28 at 2 27 56 PM](https://user-images.githubusercontent.com/35741256/139314379-85b3df73-0acb-4bae-9f4f-7bbefb5078ea.png)

**Comment by pushyamig** [comment]
We can change it
