### ISSUE TITLE
Building Block: LTI 1.3 Integration 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#23]
This issue is mainly have the LTI integrated into the CCM. [LTIJS](https://github.com/Cvmcosta/ltijs) library seems to be promising library as analyzed here #4 

CCM tool would be added at course level, more info is [here](https://canvas.instructure.com/doc/api/file.navigation_tools.html#course_navigation). 

The LTI 1.3 configuration should be only visible to admins in the course. 
Configuration of LTI tool 
Visibility: admins
Default: visible  // we can disable the tool and give an option to the user to enable it using the Setting => Navigation
$Canvas.membership.roles: Give exact users role in Canvas like Sub-Account Admin, Support Consultant etc
$Canvas.user.isRootAccountAdmin: Optional can be used to find out if user root admin or not

LTI tool Launch access list is described [here](https://docs.google.com/spreadsheets/d/1pm5y9FX0zrDX7Zy3mOyDLxmA-iKoWfmlxvbtNkWg6Zw/edit#gid=1360549473)

**Comment by pushyamig** [comment]
@ssciolla I have added some details for LTI launch fact and configuration here. This is just an FYI.

**Comment by jonespm** [comment]
During a call today I saw this project as one of the [one that used ltijs](https://github.com/txstate-etc/attendance-node)

It has an interesting pattern of using [ltijs as Middleware](https://github.com/txstate-etc/attendance-node/blob/main/api/src/lti/lti.middleware.ts) (serverless) and many of the patterns here seem pretty good to me. 

(Ignore the proxy container of the docker-compose as that's not relevant, I'm mostly just looking at the api)

UCLA had a "course requester" project but [plugged it in more direct](https://github.com/ucla/lti-course-requestor/blob/master/src/server/index.js) like how we were doing. They were using the instructure-ui frontend though.

**Comment by ssciolla** [comment]
Not sure how this got re-opened. I'm gonna close it for now.

**Comment by melindakraft** [comment]
User's appear to see or not see tool based on their role. I don't think I can validate the technical details of this issue except to say it appears to work as expected. QA passed.
