### ISSUE TITLE
Fix alignment of Select All checkbox in `SectionSelectorWidget`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#230]
Optional : Select All is strictly not centered, I feel it should be left align
<img width="1326" alt="Screen Shot 2021-10-28 at 5 11 11 PM" src="https://user-images.githubusercontent.com/8579775/139336392-19becc58-0da0-4b2d-bd40-07baff69ed39.png">
ed

_Originally posted by @pushyamig in https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/223#issuecomment-954221928_

**Comment by melindakraft** [comment]
select all alignment is working as expected
