### ISSUE TITLE
Add help link to `FormatThirdPartyGradebook.tsx`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#233]
I forgot to do this after I rebased PR #223.

**Comment by melindakraft** [comment]
@pushyami
All available tools are linking out to the correct pages. Add non-UM users is not yet complete, so there's no link to test yet.

**Comment by pushyamig** [comment]
@melindakraft, Try now. I just did a build since @ssciolla finished the Add Non-UM UI work, the Help link for this feature should be accessible. In that case we a can close one more issue :)

Note: Please make sure you change issue to `Done`.

**Comment by pushyami** [comment]
Hello,

    You have tagged the wrong pushyami again. Please remove me from this
thread.

Thanks!
Pushyami Rachapudi

**Comment by melindakraft** [comment]
Passed.
