### ISSUE TITLE
Update NodeJS, TypeScript, npm packages

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#235]
Before an initial release, we ought to do a dependency update so we are resolve any known vulnerabilities and set the project up for the future. Here are some things to note (more may be added):

- Node 16 is now the LTS: https://nodejs.org/en/blog/release/v16.13.0/
- TypeScript has had a few minor releases; we're now at [4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html).
- `@kth/canvas-api` now natively supports TypeScript, so we can remove the custom types we're using now (yay!)
- It'll probably make sense to update the NestJS dependencies at the same time (see #173).
- It will probably not make sense to tackle the Material UI 5 upgrade at the same time, since it will probably be a bigger lift. We can upgrade to the latest 4 version though (see #220).

**Comment by pushyamig** [comment]
All the version upgrades mentioned here are updated on ccm-test. 

Test Pass
