### ISSUE TITLE
Fix end-to-end test

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#237]
We have one fairly basic end-to-end test right now (`ccm_web/server/test/app.e2e-spec.ts`), which is broken because of (I believe) a session middleware configuration issue. I have done some work to fix this, doing some refactoring in `main.ts` so some code can be shared. I'll open a separate PR for this.

**Comment by pushyamig** [comment]
This is working as expected.
