### ISSUE TITLE
Back/Start Again navigation in features?

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#238]
I kinda snuck in a "Back" button and "Start Again" button to the `FormatThirdPartyGradebook.tsx` feature because I found them useful. How do we feel generally about adding these buttons to all the features (where applicable)? Currently, if the user wants to do something again, they have to go back to the Home page via `Breadcrumbs`, and then click the feature again. Adding these buttons should be relatively straightforward/fast, since we have "Cancel" buttons which do something like a "Back" already in many instances.

<img width="800" alt="Screen Shot 2021-11-09 at 6 44 23 PM" src="https://user-images.githubusercontent.com/35741256/141023557-f993d4e7-4c32-4b44-8a90-50b1ec6029e7.png">

**Comment by pushyamig** [comment]
@janelilr will give feedback on this.

**Comment by janelilr** [comment]
@ssciolla please proceed with including the "back" button for these pages. As I used the back browser button, it does take me to the home page rather than the previous step/page. The "back" button will help the user go to the previous step of the process.

**Comment by ssciolla** [comment]
As discussed earlier this week, "Back" buttons should use the outlined button style, which is the same as what is shown above for "Start Again".
