### ISSUE TITLE
should changing course name also change course code?

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#242]
My apologies for not bringing this up sooner…

I think the API for changing the course name **_SHOULD NOT_** also change the course code.  I didn't notice the course code was also being changed along with the name until recently because I didn't test the feature much.  Or maybe I didn't test it on a course with a long name.  When I did try it on my personal test course with a long name and saw that the Canvas breadcrumb navigation now stretched across the page, I noticed what was happening.

For example, before I changed my test course name, while viewing CCM the breadcrumbs had shown:

> lsloan-test > Testing Course for Lance E Sloan

After I added a couple of emoji to the end of the name, the breadcrumbs became:

> Testing Course for Lance E Sloan 🧫🧪 > Testing Course for Lance E Sloan 🧫🧪

(FWIW, I don't understand why Canvas shows the two links for the course code and name in the breadcrumbs when viewing LTIs.  They both link to the course's "home" page.  The extra link is redundant and takes up space.)

I think when someone wants to change the name of the course, they may not want to change the course code.  Although they may want the course name to be descriptive like "Introductory Astrobiology: The Search for Life in the Universe", they may want the course code to remain "ASTRO 115 001 FA 2021".

I'm thinking of labelling this issue a "bug", but I'm not sure.  Maybe it's working as intended, but the full impact of changing course code with name wasn't considered when this feature was being planned.

**Comment by pushyamig** [comment]
@lsloan The design is intentional and that's why it is working like that. But I defer to @melindakraft on further comments

**Comment by lsloan** [comment]
Understood.  So, not a bug.

However, if I were only a user of CCM, I'd be very unhappy to have my course code changed when I only wanted to change its name.

**Comment by pushyamig** [comment]
@melindakraft Can you respond to this? We are changing the Course Code apart from Course name since once of our subaccount admin Todd suggested it.

**Comment by pushyamig** [comment]
So we will be changing the course name along with course code.
