### ISSUE TITLE
Create a CCM QA instance on Openshift

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#245]
Here is the deployment notes from earlier
https://docs.google.com/document/d/1DoIZN3RVYSj3WZcERV1qggyILH65mQFaAoeOhcTMyvo/edit
https://docs.google.com/spreadsheets/d/1yREZIVhIXhLSMMzdmPfOrgr11YgftFUFRKwBwjQxe4Q/edit#gid=1341650961

**Comment by pushyamig** [comment]
I have the setup complete for ccm-test instance and launch the app from the canvas Test instance.

**Comment by ssciolla** [comment]
This all looks complete to me. We can close the issue.
