### ISSUE TITLE
"Get Sections" call enters loop when API call fails

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#249]
This isn't seen without looking at the console or backend logs (if the server is running), but it's a pretty bad bug (I'm completely to blame). Basically in the code below, when sections initially are loaded, an error is thrown, which makes this hook get called again (because `getSectionsError` is updated). I subscribed to `getSectionsError` because I wanted to be able to clear it and have it try to fetch the data again automatically. We need to add a check whether `getSectionsError` is `undefined` as well.

```
  useEffect(() => {
    if (sections === undefined) {
      void doGetSections()
    }
  }, [sections, getSectionsError])
```

To reproduce:
1) Start the application.
2) Launch in browser.
3) Shut down server only.
4) Navigate to "Format Third-Party Gradebook" tool.
5) Observe the Web console.

**Comment by pushyamig** [comment]
Test pass!. I tested this on the CCM-dev server. By stopping the server after the LTI launch. The UI display error for failing to fetch section instead of go into infinite loop
