### ISSUE TITLE
implement API to check Canvas user existence

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#252]
Related to #19 and #221.

Given a single user's `login_id`, return an HTTP status code and data to indicate whether a Canvas account exists for the user.

* **_Exists_**: HTTP 200; data including login ID, given name, surname, and ~email address~ (additional data may be helpful).  (**_NB_**: Email address is not available to the admin user token with its current set of permissions, but it is not important.)
* **_Nonexistent_**: HTTP 404; data should contain an error message and include the requested login ID for confirmation and debugging purposes.

**Comment by lsloan** [comment]
@ssciolla, do you think this API endpoint should return a simple Boolean value, or if the user exists, should it return basic information like given name, surname, and email address?

**Comment by ssciolla** [comment]
I think showing the first and last name could be helpful, but I don't know if it's necessary. @pushyamig and @melindakraft, what is your thinking? For single-user workflow, should we show the first and last name if an account with that login ID already exists in Canvas?

**Comment by pushyamig** [comment]
I feel sometime first and last name could be very long if wanted to show. @ssciolla do you have the room in the UI for it?

**Comment by ssciolla** [comment]
@pushyamig, we can make the space work regardless, we just need to compare with how the old tool works and determine whether this information is needed by the user.

**Comment by pushyamig** [comment]
The current tool is showing the first and lastname along with email address. Here is the API response from canvas when you look up user

```
[{"id":605615,"name":"FacebookCCM4 Mailinator","created_at":"2020-06-25T17:44:32-04:00","sortable_name":"Mailinator, FacebookCCM4","short_name":"FacebookCCM4 Mailinator","sis_user_id":"facebookccm4@mailinator.com","integration_id":"112760453749885@facebook.com","sis_import_id":null,"login_id":"facebookccm4+mailinator.com"}]
```
So based on these facts then I feel it is ok to show first and lastname. Screenshot for reference. 

![Screen Shot 2021-12-01 at 8 11 12 AM](https://user-images.githubusercontent.com/8579775/144240679-62a748dc-79f3-4edb-9caf-1cb0afd23c1a.png)

**Comment by lsloan** [comment]
Issue description updated.
