### ISSUE TITLE
Gradebook formatter: Submit button focuses twice.

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#256]
Category: Semantics and Structure, impact:  Minor

Issue
Submit button focuses twice.

Impact
Minor cognitive load to screen reader and keyboard only users.

Solution
It does so because it is a button inside a link. Other similar buttons (like in Add UM users) elsewhere do not follow this pattern.

**Comment by gsilver** [comment]
Nice - thanks. Only one control, no nesting or double focusing.
