### ISSUE TITLE
Footer n-nn of n will not be announced when it changes.

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#258]
Location: confirmation screen of Gradebook formatter, Add UM users, Create sections.
Impact: Critical. Type: Semantics and Structure
Issue
Footer n-nn of n will not be announced when it changes.

Impact
Screen reader users will be unaware anything has happened after a paging action.

Solution
Add aria-live="polite" to the container so that changes are announced.

**Comment by pushyamig** [comment]
@ssciolla check with @gsliver on this.

**Comment by gsilver** [comment]
aria-live="polite" for the win
