### ISSUE TITLE
Feature: Rename of Course name

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#26]
This feature is Admin/subaccount feature only. When ever the course name is updated course code needs to be updated

API: https://umich.test.instructure.com/api/v1/courses/:id?course[name]=updata course name&course[course_code]=updata course name

Details about the API listed [here](https://docs.google.com/spreadsheets/d/1pm5y9FX0zrDX7Zy3mOyDLxmA-iKoWfmlxvbtNkWg6Zw/edit#gid=578161201)

**Comment by ssciolla** [comment]
@pushyamig, can we close this now that the client and server are wired up?

**Comment by pushyamig** [comment]
Test passed!
