### ISSUE TITLE
Heading "Canvas Course Manager" should be an h1

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#261]
Location: Home
Impact: Major

Issue
Heading "Canvas Course Manager" should be an h1

Impact
Beneficial for screen readers, specially in iframed apps.

Solution
Make an h1. If framework h1 style does not suit, can override the style.

**Comment by pushyamig** [comment]
This is resolved as part of this issue #240 PR. So closing this

**Comment by gsilver** [comment]
Fixed.

**Comment by pushyamig** [comment]
Thanks @gsilver for the feedback!

**Comment by gsilver** [comment]
Fixed!
