### ISSUE TITLE
Course Rename: When editing the name, refresh the page to see in Canvas

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#263]
When editing the name, I had to refresh the page so the course name near the hamburger menu updated (upper left corner)

Suggestion: Have this update automatically or include it in the message when a course is updated such as “Course Name Saved, please refresh page”

https://docs.google.com/document/d/1v1TW2YUgiERAv_7QYSDT2d4W1e_u1A6XduSwKwAVtT8/edit#heading=h.psr28fl5pp47

**Comment by lsloan** [comment]
My suggestion would be to update just the element containing the name.  Don't refresh the whole page or instruct the user to do so.

**Comment by pushyamig** [comment]
@lsloan the course rename text is updated in the CCM once the API call is made, this issue is talking about update the Canvas courses name which is canvas. WE don't have any control to update canvas without a refresh. So @janelilr suggesting is to have a text 'refresh the page.` in the React snackbar element.

**Comment by pushyamig** [comment]
Test passed!
