### ISSUE TITLE
UM should be U-M

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#266]
UM should be U-M to stay consistent with [University Branding (Editorial Resources).](https://brand.umich.edu/editorial-resources/abbreviations/)

Janel Ilar  11:51 AM
Update on "Add Non-UM Users", it can remain as "Add Non-UM Users".

**Comment by lsloan** [comment]
Yes!  U-M not being written correctly is one of the things that annoys me.  🙂

It may be even better to use the "non-breaking hyphen" ("‑", U+2011) for this purpose to keep the "U" and "M" from being separated by a line-break.

See:
* https://en.wikipedia.org/wiki/Hyphen#Non-breaking_hyphens
* https://en.wikipedia.org/wiki/Hyphen#Unicode
