### ISSUE TITLE
Snack bar error message should show the API response reasoning for failure. 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#272]
Currently for many features that use snack bar for reporting success/failure. The error message just mention "Course rename is failed" Or Section creation has errors" instead show the message sent from the API response. 

There might be more places where this pattern might occurring. This issue should address all of then.

**Comment by pushyamig** [comment]
@ssciolla Can you give me an estimate on this issue?

**Comment by melindakraft** [comment]
I'm not testing for every error to validate all of the snack bar messages, however, I have seen this manifest and it appears messaging is working as expected.
