### ISSUE TITLE
Upgrade the Umzug to 3.0.0

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#283]
We are using Umzug library for doing the DB migrations. CCM has been using the beta version of the v3.0.0. Since it had the migration cli support which was very convenient which was not part of v2.0. 

Upgrading to this library will be next step to continues use of the CLI and other great stuff this library bring in.  

https://github.com/sequelize/umzug/releases/tag/v3.0.0

**Comment by zqian** [comment]
verified the updated Umzug version.
