### ISSUE TITLE
Further minimize prod dependencies by pruning webpack packages

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#29]
This works out pretty nicely in development, but it's a little awkward having to import `webpack` and related dependencies even in the production images. Now or later, we might want to think about a separate `dev` `app.ts`. Alternatively, we could use `webpack-dev-server`, but that starts to look similar to `react-scripts`. There might be a way to run two servers in one container? I haven't thought that through too much.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/24#discussion_r588590806_

**Comment by ssciolla** [comment]
We switched to using `webpack --watch` as a separate process in https://github.com/ssciolla/canvas-course-manager-next/pull/1 (PR to my LTI PR branch, #40), which allowed us to move all the loaders and `webpack` stuff to `devDependencies`. This should be resolved now.

**Comment by pushyamig** [comment]
Test passes. We don't use the webpack-dev-server anymore. This was changed early on. We now was webpack --watch as part of the `package.json` configuration
