### ISSUE TITLE
let external users approve `terms_of_use` themselves?

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager-next#291]
## Problem

When the external user enrollment feature of the API was implemented, one of the keys sent to the Canvas API is `"terms_of_use": true`.  Canvas seems to work if that value isn't specified, but at the time it seemed like it would be safer to specify it explicitly.

That resulted in the conversation…

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/247/#r773362559_
> I wish there was a way for folks to approve the Terms of Use themselves...

_Originally posted by @lsloan in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/247#r773424242_
> I **_think_** this will work without specifying the `terms…` key.  I could remove it, if you prefer.  I think I chose to use `true` here, because I read that's the default value Canvas users if it's not specified.

## Solution

If it makes sense to do so, either remove the `terms_of_use` key from the request or explicitly set it to `false`, whichever will give the desired behavior.

It would be helpful to get @melindakraft's input on this.

**Comment by ssciolla** [comment]
@lsloan, can you determine whether the new user is prompted to accept terms of use in the cases where this is `true` and `false`? Melinda thinks it's preferable if the user has to accept the terms themselves.

**Comment by jonespm** [comment]
When I create a user through the regular UI it doesn't set this parameter at all, it's not required. I'm not seeing where the default is true.

This is the prompt the user ends up with, at least from the dev instance. This seems like what we'd want, and should be obtained either setting false or not setting. Unless our prod instance is configured differently from dev to not require anyone to accept terms. In that case false or not setting still seems the best we can do.

![image](https://user-images.githubusercontent.com/27447/148408132-cc9020e4-0339-4acc-8a5e-a1b6ee09996b.png)

**Comment by pushyamig** [comment]
I don't see `terms_of_use` parameter set as part of API.  test passes
