### ISSUE TITLE
When session expires, user may not be able to initiate new session via LTI launch

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#300]
Something like this was reported by Dan, but I have also experienced it on occasion as well. Currently, sessions expire after 24 hours. When this occurs, sometimes (or all the time, this needs more testing) an error is thrown in the console but subsequent attempts to relaunch the application via the external tool link in Canvas fail. Instead they see the standard unauthenticated view.

Users should be able initiate a new session by launching the LTI tool again when this occurs. A better error message than the generic authentication failure would also be helpful.

This needs more research.

**Comment by melindakraft** [comment]
We are unable to find the perfect storm of replication steps. Dan reports that he had many tabs open and had been in and out of Canvas both as himself and while masquerading. The error message he received was “You were not properly authenticated to the application.” He also stated that since he knows deleting the auth will fix things, he didn't try launching a new session or taking other steps to fix the problem. 

This may be an edge case which is solved by other steps (relaunching the tool) that doesn't need further investigation at this time.

**Comment by ssciolla** [comment]
@pushyamig, do you have time to look at this? I think it happened to @janelilr last week. My hunch is that some cookie has expired, but it is not getting reset properly when a new launch happens. Perhaps the session needs to be destroyed manually after we throw the error, maybe in `SessionGuard` in `auth/session.guard.ts`. You should be able to try to reproduce the issue effectively by setting the `MAX_AGE_IN_SEC` environment variable to something like `120`. There may be more complexity hidden here (JWT cookie expiration?), but that's where I'd start.

**Comment by pushyamig** [comment]
OK. I myself noticed it. We should fix it. I will take a look at it.

**Comment by pushyamig** [comment]
My Research around this issue is captured [here](https://docs.google.com/document/d/1Mtj4Kx4rz-La5RvBXEGeD5nrlQ7iOxeT-0WYgjGwcuU/edit)

**Comment by lsloan** [comment]
I've QA tested this according to the test plan in the description of this issue.

When the maximum age of cookies is set to 60 seconds, performing the specified operation does produce an error, as expected.  Refreshing the page gets new cookies and is good for another 60 seconds.  So, in that regard, this issue passes QA testing.

![image](https://user-images.githubusercontent.com/20786/162290447-7a888a21-c643-4960-8af3-1d92e64ef7de.png)

**Comment by lsloan** [comment]
However, as the description of this issue also suggests, the error message shown is very general.  It would help to have a more specific error message and advice to the user.

**Comment by lsloan** [comment]
Moved this to "[Done](https://github.com/tl-its-umich-edu/canvas-course-manager-next/projects/1#column-16254110)", since there wasn't any discussion about it in [Slack](https://umich-its-annarbor.slack.com/messages/G0130F688N6/p1649363722937869).

**Comment by pushyamig** [comment]
@lsloan Sorry I missed the conversation, it will do in the done column. I think you suggestion after testing are great and will look into next phase. Thanks for testing!
