### ISSUE TITLE
`InvalidTokenInterceptor` should not intercept all `401` responses from Canvas

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#305]
This problem arose during discussions with the penetration testing team. Currently, the `InvalidTokenInterceptor` -- which was designed originally to delete invalid Canvas tokens (see #101) -- is catching all HTTP exceptions with status code `401` originating from Canvas.

I believe this was done originally because it seemed a more durable and programmatically safe way to identify the responses (rather than comparing string body messages which Canvas may opt to change). In addition, the user would have to hit the API directly to produce a `401` not related to an invalid token (for example, the UI won't let them request a different course that they don't have access to, but a direct API call would produce a `401`).

However, this became a problem for penetration testers, because they are hitting the API directly with lots of parameter values, and the token deletion and redirects block from a scan from continuing. Thus, for at least some use cases, we need a way to differentiate between `401` errors. We could allow the interceptor to be turned off or on, but we could also process the responses and only delete tokens when the response body has "Invalid access token." or "Insufficent scopes on access token.".

**Comment by pushyamig** [comment]
Test passes, This is working as expected
