### ISSUE TITLE
Error when launching CCM in Safari

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-course-manager-next#312]
When launching CCM from Safari on Canvas beta this error returns

`{"status":401,"error":"Unauthorized","details":{"description":"Error validating ltik or IdToken","message":"MISSING_VALIDATION_COOKIE"}}`

I believe this is a common issue with Safari if a user has the default Privacy option "Prevent cross-site tracking" checked. I saw it was [brought up as an issue in the library](https://github.com/Cvmcosta/ltijs/issues/53) but there was no resolution. The resultion by most other vendors is either turn this setting off or switch to a vanity URL, which we've been in the process of doing but isn't complete.

I tested on Canvas Test which does have a vanity URL and it works fine. However this will be the same in prod as it is in beta.

Our python apps that use pylti13 prompt to open a new window. That's because there's [javascript to check for this](https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/cookies_allowed_check.py) in the library. Since the majority of our users are on Safari this might be something we need to address and at least prompt users to open in a new window or disable this option. 

IMS LTI team is working on a solution to avoid this by using postMessage rather than cookies but this isn't yet in the spec.

**Comment by pushyamig** [comment]
@melindakraft , Can you suggest the user message telling about the error?

**Comment by melindakraft** [comment]
`It seems your browser is blocking 3rd party cookies which are required for this application. To resolve this issue, please update your settings for <a href="https://support.google.com/chrome/answer/95647?hl=en" target="_blank"> Chrome</a>, <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/12.0/mac/10.14" target="_blank"> Safari for MacOS</a>, <a href="https://www.whatismybrowser.com/guides/how-to-enable-cookies/safari-iphone" target="_blank"> Safari for iOS</a>, <a href="https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?redirectslug=enable-and-disable-cookies-website-preferences&redirectlocale=en-US" target="_blank"> Firefox</a>, and <a href="https://www.whatismybrowser.com/guides/how-to-enable-cookies/edge" target="_blank"> Microsoft Edge</a> to allow 3rd party cookies.`

**Comment by ssciolla** [comment]
@melindakraft, @pushyamig, working on this now. A thought occurred to me: should all these browser specific links be in the help docs or on this page? I could see arguments for doing it either way.

**Comment by pushyamig** [comment]
We can create a generic separate error pages in documentation and we can link to that page.

**Comment by melindakraft** [comment]
Error messaging works as expected. This might be a nuance of my Safari, but the only way I can get the links to the browser support resources to work is to right click on them and open in a new tab.
