### ISSUE TITLE
Change tab order on home page, highlight and ripple card on hover, click

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#318]
Currently, when the user navigates via keyboard on the home page, there are several extra items in the tab order which can't actually be interacted with via "Return". We should take a look at the implementation in `FeatureCard.tsx` to ensure the tab and click behavior makes sense. We could also add highlighting on hover or other action styling.

**Comment by gsilver** [comment]
Tab order is logical, visible, and there are no invisible elements in the tab order.
