### ISSUE TITLE
Add a Cache Control header for not caching the API response

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#320]
It is recommendation that don't cache any sort of API response on the Client side. So Adding a Cache-Control header is way to go about it. 

Looking at all the Cache Control header options `Cache-Control: no-store` fits the requirement.  While it is easily deceptive to think `Cache-Control: no-cache` it won't caching but what that tell the browser is cache the response in the local store and revalidate with server if this value changed before presenting to the user

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#the_cache-control_header

**Comment by ssciolla** [comment]
This seems to be working as expected. I QAed on the test instance. Static files are cached; HTTP requests are not. Moving to Done.
