### ISSUE TITLE
Observe and plan for ecosystem move to ECMAScript Modules

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#330]
There is a more recent version of `p-limit`, version `4`, but it uses ESM, which would require some tinkering with `package.json` and `tsconfig`s, and maybe more dramatic import changes across the project. This should probably be handled separately, and it may not be urgent. I need to do more reading about it. See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c and https://www.typescriptlang.org/docs/handbook/esm-node.html

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/327#discussion_r798894673_

I've done some more research on this. I will add more links below as I find them:

Resource(s):
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
- https://www.typescriptlang.org/docs/handbook/esm-node.html
- https://nodejs.org/api/esm.html
- https://dev.to/asteinarson/typescript-nodejs-and-es6-esm-modules-18ea

Library standpoints:
- https://github.com/sindresorhus/got/releases/tag/v12.0.0
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
---------------------------------------------------------
Test Plan
**Functional testing:** This is full feature/regression testing
1. **Development testing**
   1. Test all features
   2. test the bulk upload of Add U-M user and Bulk create sectiosn
   3. OAuthflow needs to be tested. Testing focus on token could be read, update, delete
      1. Delete the token from Canvas Profiles - > setting 
      2. Let the token Refresh
      3. By 'Become user' feature
   4. Test the Database Migration. Do this by creating a new DB i.e deleting `.mysql_data` so DB could be created. So migrations could be applied. 
       1. Use the migration commands from ReadMe
       2. Trying this from doing a local Prod build/up using `docker-compose-prod.yml`

**Comment by pushyamig** [comment]
Should this be in icebox?

**Comment by ssciolla** [comment]
> Should this be in icebox?

Yes, I don't think we should tackle this immediately, too many things still in motion it seems.

**Comment by ktowneUM** [comment]
Quickly tested all features
Tested the bulk upload of Add U-M user and Bulk create sections
Deleted the token from Canvas Profiles - > setting
Let the token Refresh
Used the 'act as' feature to test a teacher accessing CCM

**Comment by ktowneUM** [comment]
I can't test the database migration

**Comment by pushyamig** [comment]
Dev test plan was provided is for when reviewing PR and checking that. I think it is already taken care so I will move the issue to Done column
