### ISSUE TITLE
Add footer with copyright statement

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#347]
As discussed in meetings, the UI might benefit from a Copyright statement at the bottom of the page in a footer. This follow standard practice in ITS, but also helps the user identify the institution responsible for the tool.

Some of our other applications use a flat page to set the copyright statement; others just hardcode it in templates. We can hardcode it for now or research ways to send it in the JavaScript bundle, similar to #331.

**Comment by melindakraft** [comment]
Validated footer is displaying consistently in all CCM application areas.
