### ISSUE TITLE
Make Swagger link easier to use

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#353]
This change was proposed by @lsloan. It may help backend developers if the Swagger UI link was adjusted as follows:

1) It was moved to the top of the page.
2) It used `target="_blank"` so the CSRF token was easily available.
3) It was labeled or contained so it was apparent it was a development mode tool.

**Comment by pushyamig** [comment]
No issue were found after moving the link to top of the page. Test passes
