### ISSUE TITLE
 gradebook tools download file name needs to be fixed

### ISSUE THREAD

**Issue by melindakraft** [tl-its-umich-edu/canvas-course-manager-next#358]
When the gradebook file is generated, its name is "third_party_gradebook_puff.csv." or "Canvas_gradebook_geff.csv

This name needs to be fixed to not include "puff." It would seem the most useful name for the user would be some combination of the original filename and the words "formatted" or "canavas-formatted." 

Whatever we decide, it should not include the word "puff/geff" which is just an internal acronym for one third party tool.

**Comment by pushyamig** [comment]
@melindakraft I think it is same for GEFF tool as feel. Do you think you need to change over there as well

**Comment by melindakraft** [comment]
confirmed word "formatted" is added to the downloaded file and the rest of the file's name matches the original file.
