### ISSUE TITLE
Create General purpose components that is used across the feature

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#36]
Since Backend is still work in Progress but UI work can be done independently. Like building of breadcrumbs,  Stepper, Pagination list etc. As per the mockups adding the accessibility support during this time is more pratical

**Comment by pushyamig** [comment]
@chrisrrowland do you think we need to close this issue? I feel that this issue served the purpose

**Comment by chrisrrowland** [comment]
> @chrisrrowland do you think we need to close this issue? I feel that this issue served the purpose

Yeah closing it makes sense.  I think it's pretty vague to be an issue anyways :)
