### ISSUE TITLE
Make number of `pm2` threads configurable

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#375]
For flexibility in testing and deployment related to memory limits and performance, it makes sense to make the number of threads per pod or container. This is set in `ecosystem.config.js`, and we can use a similar pattern as we already do for `PM2_MEM_LIMIT`.

**Comment by pushyamig** [comment]
I will QA this

**Comment by pushyamig** [comment]
I have tested this ccm-test. I added the configuration variable. The default seems to be 4 threads. I changed value to 3 and app launches fine. Currently it is set to 4 might change it later. Test passes
