### ISSUE TITLE
Adopt a logging approach for server

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#38]
Thus far we've been mainly using `console.log` and `console.error`, but there are likely better ways to approach this so that we can include timestamps and log origin, as well have access to more levels like `debug`.

[`Log4js`](https://www.npmjs.com/package/log4js) and [`winston`](https://www.npmjs.com/package/winston) seem like popular options with TypeScript support.

In addition, those of us from Django backgrounds will miss request logging. There is express middleware for this; [morgan](https://www.npmjs.com/package/morgan) seems like a popular option.

**Comment by pushyamig** [comment]
Test passes. I don't see any console log message in the server folder of ccm_web and a configuration of log level is established as well
