### ISSUE TITLE
Support ARM containers for launching mysql 5

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#388]
Added the platform option in `docker-compose.yml`, since the current MySQL image does not support ARM containers (Apple M1 is an ARM-based system).

References:
https://docs.docker.com/desktop/mac/apple-silicon/#known-issues
https://devcoops.com/no-matching-manifest-for-linux-arm64-v8/

**Comment by ssciolla** [comment]
This may be useful: https://github.com/tl-its-umich-edu/canvas-app-explorer/pull/187/files

**Comment by jonespm** [comment]
Thanks! Our ultimate solution was to switch the image to 

`    image: mysql/mysql-server:8.0
`

And renaming
`      - MYSQL_TCP_PORT=3306
`

**Comment by pushyamig** [comment]
@jonespm CAE seems to uses `image: mysql:8-oracle` and I looked at the Myla it uses `image: mysql/mysql-server:8.0`, What is the recommended? and should we not stick with same image?

**Comment by jonespm** [comment]
MyLA needs to be updated to the one that CAE is using. We just didn't want to add that to the release we did on Wednesday. 

Recommended to use `mysql:8-oracle` since it works better on non-linux platforms and uses a more similar to config to what we were using.
