### ISSUE TITLE
Course ID from LTI launch is now a string

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#402]
Following the latest Canvas [changes](https://community.canvaslms.com/t5/Canvas-Change-Log/Canvas-Platform-Breaking-Changes/ta-p/262015), LTI variable substitution values are always going to be strings. We treat the course ID from the launch now as a `number`; it doesn't seem to cause any errors, but the type is wrong. This should be fixed and explicitly cast. We could also expect one of the two types and do some type checking and casting.

Referace: https://community.canvaslms.com/t5/Canvas-Change-Log/Canvas-Platform-Breaking-Changes/ta-p/262015

**Comment by pushyamig** [comment]
The Change of course id type is implement in this project https://github.com/tl-its-umich-edu/canvas-app-explorer/commit/e6fc3ac1167f86e7574ded62304fdb406cd1aee3. 
(But this is Django, but the approach used could be taken)

**Comment by pushyamig** [comment]
I will QA a This. since this is code releated

**Comment by pushyamig** [comment]
Test Passed: the LTI launches happens and the course ID is casted to right type which is string. Tested with multiple roles
