### ISSUE TITLE
Update backend dependencies

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#404]
We'll need to update the project's backend dependencies in the near future. This will likely include moving to Node 18, NestJS 9, and picking up updates to other miscellaneous backend packages. We may also want to look at #330 in the process, though we may not quite be there yet.

Update:
Node 20 is currently on LTM
NestJs 10

**Comment by ktowneUM** [comment]
quick testing of main functionality
