### ISSUE TITLE
UI component & styling bugs (FE Dependencies)

### ISSUE THREAD

**Issue by jaydonkrooss** [tl-its-umich-edu/canvas-course-manager-next#418]
Component and styling bugs found while doing dependency upgrade (mainly [material UI update](https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/417)):

  - Pagination is broken
  - Error window is broken (Try again window)
  - Error icon is red (Review your CSV file) color is changed to blue
  - Alignment issue b/w small and big window inside features workflow
  - Progress bar is close to the section selection window
  - Unmerging text/spinner is missing when unmerging feature 
  - Gradebook formatter requirement list is broken

**Comment by ktowneUM** [comment]
Verified:
Pagination is broken
Error window is broken (Try again window)
Error icon is red 
(Review your CSV file) icon color is changed to blue
Progress bar is close to the section selection window
  add non-um > multiple users
  add um-users > single section
Unmerging text/spinner is missing when unmerging feature
Gradebook formatter requirement list is broken
