### ISSUE TITLE
Selecting a section doesn't have a grey background

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#427]
Some where during the Upgrade of MUI v5 this is broken
**Features affected: Merge Section, Add-U-M user, Add Non U-M User, Format Third‑Party Gradebook.** (All features where section selection is allowed)

**Expected:** 
![Screenshot 2024-04-03 at 9 18 36 AM](https://github.com/tl-its-umich-edu/canvas-course-manager-next/assets/8579775/9d11ef7d-0920-4021-8e6c-1cdec7a52b93)
**Actual:**
![Screenshot 2024-04-03 at 9 18 29 AM](https://github.com/tl-its-umich-edu/canvas-course-manager-next/assets/8579775/83ae9670-7b1d-4c52-b5a5-579eb01c49c2)

**Comment by ktowneUM** [comment]
tested Merge Section, Add-U-M user, Add Non U-M User, Format Third‑Party Gradebook

selected sections have gray backgrounds
