### ISSUE TITLE
Add Non U-M User: spinner background is applied to entire CCM screen view

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#428]
Currently when choosing the option `Add multiple users by uploading a CSV` and as you enter the view , a GET section call is made. It fetches section but the while that action is happening the spinner grey background should only be applied to the unit where the section are and not to the entire CCM window

**Comment by ktowneUM** [comment]
The spinner background is only applied to the section list
