### ISSUE TITLE
CCM Docs: copyright should have dynamic year and version updates to bootstrap

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#437]
Currently CCM doc is hosted on Github pages. So a checking to `main` causes a change to prod version

Changes needed
1. Copyright at the footer should have a dynamic year generatiion
2. The Site is powered by Bootstrap, update to latest version using CDN

**Comment by ktowneUM** [comment]
Documentation linked from the Need Help? link on all pages displays 2024 as the year in the footer
