### ISSUE TITLE
Allow for direct routing on client side

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#48]
There is currently an issue with the server configuration where you cannot navigate directly to a specific page after `/` directly by URL. I think this has something to do with how `webpack-dev-middleware` works (see issue below).

https://stackoverflow.com/questions/43921770/webpack-dev-middleware-pass-through-for-all-routes

**Comment by ssciolla** [comment]
PR #40 modified the `webpack` approach and requires an LTI integration, so the situation has changed here a bit. I think this is no longer an issue, because the code below will pass requests like these through to the client. However, we may need to do some more research on this, since I don't know how the LTI validation affects this. This is also probably low priority, since users don't see and can't easily change the route directly.

https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/3f7536de69f87cbe80902473209f874aefb1e270/ccm_web/server/appHandler.ts#L92-L95

**Comment by pushyamig** [comment]
@ssciolla is this still relavent?

**Comment by ssciolla** [comment]
I need to do a little testing, I think it's still an issue, but again, it doesn't impact users really, since the URL is hidden from them with the Canvas iframe anyway.

**Comment by pushyamig** [comment]
May be ICE box, need to think about it

**Comment by pushyamig** [comment]
Test passes
