### ISSUE TITLE
Switch from PostgreSQL to MySQL

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#49]
In order to save costs and limit barriers to collaboration, we decided to change the database technology from PostgreSQL to MySQL. However, changing this is currently blocked by a bug in `ltijs-sequelize`: https://github.com/Cvmcosta/ltijs-sequelize/issues/2 For now, we can stick with PostgreSQL for finishing #23, and we can make the change once `ltijs-sequelize` is updated.

**Comment by pushyamig** [comment]
@ssciolla Do you see this bug in `lti-sequelize` getting solved soon? Can you you point me what exactly the bug is.

**Comment by ssciolla** [comment]
Sorry, I meant to link to that, I'll add it to the issue.

**Comment by ssciolla** [comment]
> Sorry, I meant to link to that, I'll add it to the issue.

Done.
