### ISSUE TITLE
Research on external Canvas API wrapper availability

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#5]
Research on Canvas API wrapper that will be useful to making canvas API calls 

2 Libraries for Canvas API wrapper is available 

1. https://github.com/ubccapico/node-canvas-api, this is maintained by UBC but only support certain api call but doesn't have a generic wrapper taking any URL for HTTP call like GET/POST/PUT/DELETE. Looks this the last commit was in OCT 2020. We can talk to UBC if we need add any API calls
2. https://github.com/byuitechops/canvas-api-wrapper, This support both generic and Non Generic API calls. This did not had a commit since 2019.

Here is the library [comparision](https://docs.google.com/spreadsheets/d/1Y-MO-cSogKgFB2Ms8r3Ra7uwA6LPPXkpD3OhzldHtfI/edit#gid=0) that put together so far

**Comment by pushyamig** [comment]
@jonespm, can we close this issue?

**Comment by pushyamig** [comment]
Done the research, closing now

**Comment by jonespm** [comment]
This seemed to be the best library but we'll still have to write some code to wrap this. 
[Canvas API client](https://github.com/kth/canvas-api)
