### ISSUE TITLE
Create global UI style/theme

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/canvas-course-manager-next#75]
Not sure what the correct terminology but we should be using some sort of global theme/style throughout the application.

This seemed to me like something you might implement after having more than one feature so you have an idea of common concepts, though it couldn't hurt to have the framework in place earlier.

Currently each component is composing its own style.

**Comment by pushyamig** [comment]
@ssciolla Can you provide some estimation here?

**Comment by ssciolla** [comment]
Well, it depends on what this issue is. If it's implementing a global theme, I can estimate that, but fixing the problem you identified may involve updating to Material UI 5, which is a bigger deal, harder to estimate. These should be split into separate issues.

**Comment by pushyamig** [comment]
I am talking about the error, possible fix which I understood as having a global theme, if that is not the case. I feel we need to evaluate if we can live with this error for sometime or upgrade to Material UI.

**Comment by ssciolla** [comment]
Okay, I gave an estimate. I still think that needs to be a separate issue. It's related but not the same as what Chris originally opened this issue about.

**Comment by chrisrrowland** [comment]
I believe I did some investigating, and that led to some article that led to me to experimenting w/ a theme to eliminate the warning message.
I don't remember why the theme solved it, but since we wanted to implement a global theme anyways it seemed like a reasonable solution.
