### ISSUE TITLE
Canvas Gradebook Formtter user response text 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#77]
This issue mainly deals with adding a suitable response text for Following scenarios.

1. When user launches the Canvas Gradebook converter 
2. User loads a csv file with no schema applied validation error
3. User loads a csv file when current and final grade don't match validation error occur
4. User successfully passes all the validation error and ready for download to [Faculty center](https://csprod.dsc.umich.edu/htmldoc/eng/dftie/lsaa/htm/CU_SGRD_Upload.html)
Direct link to upload the formatted gradebook
https://csprod.dsc.umich.edu/psc/csprodop/EMPLOYEE/SA/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL?

**Comment by pushyamig** [comment]
Case 4: 
![Screen Shot 2021-05-06 at 7 22 12 AM](https://user-images.githubusercontent.com/8579775/117665591-00eec180-b171-11eb-9dc7-b4520195fd61.png)

**Comment by pushyamig** [comment]
Case 1:
![Screen Shot 2021-05-06 at 11 06 29 AM](https://user-images.githubusercontent.com/8579775/117665854-43b09980-b171-11eb-9e01-f5360ad4e51e.png)

**Comment by pushyamig** [comment]
Case 2:
![Screen Shot 2021-05-06 at 11 05 15 AM](https://user-images.githubusercontent.com/8579775/117666016-6b9ffd00-b171-11eb-8bdc-0224e707bfd9.png)

**Comment by melindakraft** [comment]
Case 1: This tool reformats an exported Canvas gradebook file for upload to Faculty Center.  (replace the text that says The CSV will be reformatted....)

Requirements  (not requirement needed and put them in this numerical order on the page with links to relevant Canvas docs:
1. All assignments are graded. (link out to this doc, which lists all gradebook options: https://community.canvaslms.com/t5/Instructor-Guide/tkb-p/Instructor#Grades)
2. Grading scheme must be enabled in your course settings. (Link out to Canvas doc: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-enable-a-grading-scheme-for-a-course/ta-p/1042 
3. You have exported (downloaded) the completed Canvas gradebook. (Link out to Canvas Doc: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-export-grades-in-the-Gradebook/ta-p/809)

Case 2: Remove "review your CSV file" and replace with "Grading Scheme must be enabled in course settings." I would expect that the link on "Grading Scheme must be enabled" would be to this Canvas doc: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-enable-a-grading-scheme-for-a-course/ta-p/1042 

Case 3: There are validation errors. Get help with validation errors. (get help link goes to a help document)

Case 4: File validation successful.

**Comment by pushyamig** [comment]
@chrisrrowland you can work on this next as that will make 95% feature complete for Canvas Gradebook converter

**Comment by chrisrrowland** [comment]
Should this be removed?
![image](https://user-images.githubusercontent.com/17617998/121194555-d742bc00-c83c-11eb-8360-97166043909e.png)

**Comment by chrisrrowland** [comment]
> Case 2: Remove "review your CSV file" and replace with "Grading Scheme must be enabled in course settings." I would expect that the link on "Grading Scheme must be enabled" would be to this Canvas doc: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-enable-a-grading-scheme-for-a-course/ta-p/1042

You've asked for the top line of text to be replaced with "Grading Scheme must be enabled in course settings." and given details for the link in "Grading Scheme must be enabled" (which only appears in this new text)

What becomes of the 2 items listed below it?

**Comment by melindakraft** [comment]
@chrisrrowland @pushyamig Grading scheme must be applied before a letter grade will appear in the downloaded Gradebook. Since this is addressed in #2 already, this sounds like redundant info and hte statement should be removed.

I could see a file failing validation for no letter grades, which is when we'd remind the user to set the grading scheme, but if this message is not serving as a validation error message, it can be removed.

**Comment by chrisrrowland** [comment]
> Case 3: There are validation errors. Get help with validation errors. (get help link goes to a help document)

What document?

**Comment by chrisrrowland** [comment]
Trying to decipher exactly what is being asked for here.. feels like the best way is to just show screenshots.  @melindakraft  is this what you had in mind?

I still need to know the help document for validation errors.

![image](https://user-images.githubusercontent.com/17617998/121230750-a1fa9600-c85d-11eb-94de-f819ca5562a7.png)
![image](https://user-images.githubusercontent.com/17617998/121230803-b2127580-c85d-11eb-9bf8-adcda61e2775.png)
![image](https://user-images.githubusercontent.com/17617998/121230871-c0609180-c85d-11eb-9862-eb10104d334c.png)
![image](https://user-images.githubusercontent.com/17617998/121230942-d1110780-c85d-11eb-8d11-06bd040cb9bf.png)
![image](https://user-images.githubusercontent.com/17617998/121230976-d79f7f00-c85d-11eb-80f4-883f353a456d.png)

**Comment by melindakraft** [comment]
This looks good to me. I like the grid display that shows override grades
and the not-overridden grades.

Second screenshot where grading scheme is missing - they don't need a
prompt to upload again. A link to the Course settings would be more
appropriate b/c after they turn on grading scheme, they will have to
re-export the gradebook before running in back through GEFF.

*Melinda Kraft, Service Manager for Learning Management*

*ITS Teaching & Learning*

131 Boyer Building, Ann Arbor, MI 48109-3704

734/763-0509 <+17347630509> | she, her, hers


*Need help with online instruction? Join the Teaching Online with Canvas
Workshops: From Good to Great!
<https://its.umich.edu/training/canvas> | Workshop Video Playlist
<https://www.mivideo.it.umich.edu/playlist/dedicated/137537371/1_bc51ybxg/1_fart74iy>*

**Comment by chrisrrowland** [comment]
@melindakraft So we want a link to instructions that say how to enable the grading scheme (1st item in list) and instead of upload, a link to the course settings?  (That 2nd part will have to wait for back end support so it can't be part of this particular issue)

**Comment by chrisrrowland** [comment]
@melinda 

> > Case 3: There are validation errors. Get help with validation errors. (get help link goes to a help document)
> 
> What document?

@melindakraft  what is the link referred to here?

**Comment by chrisrrowland** [comment]
> @melinda
> 
> > > Case 3: There are validation errors. Get help with validation errors. (get help link goes to a help document)
> > 
> > 
> > What document?
> 
> @melindakraft what is the link referred to here?

![image](https://user-images.githubusercontent.com/17617998/121358126-5a791600-c900-11eb-9788-bb242eeb7348.png)

**Comment by pushyamig** [comment]
@melindakraft Can you respond to above comment?

**Comment by melindakraft** [comment]
@chrisrrowland @pushyamig 
_what is the link referred to here?_

We don't have a home yet for help docs. Should we open an issue to make that decision?

**Comment by pushyamig** [comment]
> We don't have a home yet for help docs. Should we open an issue to make that decision?

I am keeping track of documentation as an [epic](https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/110) (Umbrella issue). This is [issue](https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/79) for creating documentation page and issue for wiring the links in the UI is [here](https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/78) 

I don't feel we have help thing wired up yet. So we need to wait. But we can create an issue with missing link in the user Response here

**Comment by pushyamig** [comment]
Test passed!
