### ISSUE TITLE
Add OpenAPI/Swagger implementation

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#82]
OpenAPI and Swagger are common tools for documenting and allowing users to try out custom-built server API endpoints. Nest provides a library and patterns for adding this easily to an existing Nest application. We would need to also figure out how to access the UI created by Swagger while using the `ltijs` authentication.

- https://docs.nestjs.com/openapi/introduction
- https://swagger.io/

**Comment by pushyamig** [comment]
Test passes. I see swagger added for local development and not when running in on non-prod servers
