### ISSUE TITLE
Make the sample CSV file as downloadable file instead of pop-up in Create sections feature

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#89]
Currently the sample CSV file is a pop up, from user's perspective it is simple we give then a Downloadable CSV file. The downloadable file should have following 
1. Should have the File header `SECTION_NAME`
2. static one row section name as `Section 001`
3. File name as `sections.csv`

The Bullet list is a guideline of what is expected of given file.

**Comment by pushyamig** [comment]
@chrisrrowland This could be the next issue you can work on

**Comment by chrisrrowland** [comment]
Do we just want it to look like this then?

![image](https://user-images.githubusercontent.com/17617998/121696750-626cbd80-ca9a-11eb-9a33-2e8e61e78261.png)

**Comment by pushyamig** [comment]
Test passes. Tested by Kristine Towne
