### ISSUE TITLE
Control verbosity of Sequelize

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#91]
Currently, the logs include detailed SQL statements for each database transaction. This is useful but probably not desirable in all situations. This should be configurable.

https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/4a9bbe78b4a7c0673d0bfbe01efb5e20b95ddcad/ccm_web/server/src/app.module.ts#L13-L39

The configuration for this should be added using a `logging` property in the `useFactory` function return above.

**Comment by pushyamig** [comment]
Test passes.
