### ISSUE TITLE
Failing to insert user records when using capitalized `User` table name in some cases

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#93]
@chrisrrowland reported an issue where the application failed to insert user records upon LTI launch using the table name `User` (the actual table name is `user`). @pushyamig and I could not reproduce the issue. However, it seems specifying `tableName: 'name'` in `user.model.ts` will resolve this for him (and doesn't affect me). I'll create an PR.

We should keep an eye on this problem, as we still don't know why we experienced different things. Using `tableName` in the `@Table` decorator is probably something we should do in all model definitions.

**Comment by pushyamig** [comment]
test passes. since now all tables name are added in the respective models file for user and canvas_tokens
