### ISSUE TITLE
Figure out functional session approach using express-session

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-course-manager-next#95]
As part of implementing an OAuth workflow (see PR #92) and storing LTI launch information, we need to be able to store some state (e.g. the `ltiKey` and `userLoginId`) in temporary storage, ideally a session using [`express-session`](https://www.npmjs.com/package/express-session) that is retrievable using the `Request` object and persists 1) between route changes on the application's domain and 2) (maybe not possible) during the redirect to and back from Canvas.

In our work-in-progress, we are having trouble getting sessions to persist on the request object in both cases 1 and 2 above. Sessions are stored in the database, but they are not being picked up on new requests; cookies may not be working properly. Below are possible reasons (which we can hopefully rule out systematically):

- [ ] Session library setings
- [ ] Cookie settings
- [ ] Proxy settings  or `ngrok` tunneling in local development
- [ ] Other security settings (e.g. CORS/CSP)
- [ ] `ltijs`

This work is related to #22 and #45. More info will be added as research continues.

SessionID changing behavior with every request/response
![ezgif com-gif-maker](https://user-images.githubusercontent.com/8579775/120812400-f11d8f80-c51a-11eb-91c0-f2dbb46b29c0.gif)

**Comment by pushyamig** [comment]
Test passes. lot changed in the implementation since the issue created. App is working as expected based on the testing(penn, QA testing) that is happening.
